config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :books, except: [:new] do
  	resource :favorites, only: [:create, :destroy]
  	resource :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :follows, :followers
    end
  end

  post 'follow/:id' => 'relationships#follow', as: 'follow'
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'

  get '/search', to: 'search#search'

  get "home/about" => 'homes#about'
  root 'homes#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :follower, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followed, foreign_key: "followed_id", class_name: "Relationship", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end

  def self.search(search)
    return all unless search
    where(['name LIKE ?', "%#{search}%"])
  end

  attachment :profile_image
  validates :name, presence: true
  validates :name, length: { in: 2..20 }
  validates :introduction, length: { maximum:50 }
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
  before_action :correct_user, only: [:edit]

  def index
  	@users = User.all
    @book = Book.new
  end

  def show
  	@user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  	  flash[:notice] = "You have updated user successfully."
  	  redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def follows
    @user  = User.find(params[:id])
    render 'follows'
  end

  def followers
    @user  = User.find(params[:id])
    render 'followers'
  end

  private
  def correct_user
    user = User.find(params[:id])
    if user != current_user
      redirect_to user_path(current_user)
    end
  end

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="4"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
    <tr>
      <td><%= attachment_image_tag user, :profile_image, size: "50x50", class: "img-rounded pull-left", fallback: "no_image.jpg" %></td>
      <td><%= user.name %></td>
      <td>フォロー数：<%= user.follower.count %></td>
      <td>フォロワー数：<%= user.followed.count %></td>
        <% if current_user.following?(user) %>
          <td><%= link_to 'フォロー外す', unfollow_path(user.id), method: :post %></td>
        <% else %>
           <td><%= link_to 'フォローする', follow_path(user.id), method: :post %></td>
        <% end %>
      <td><%= link_to 'Show', user_path(user) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_side.html.erb
<% if flash[:notice] %>
  <div class="flash">
    <%= flash[:notice] %>
  </div>
<% end %>

<h2>User info</h2>
<table class="table">
  <tbody>
      <tr>
        <td><%= attachment_image_tag user, :profile_image, size: "100x100", class: "img-rounded pull-left", fallback: "no_image.jpg" %></td>
      </tr>
      <tr>
        <td>name</td>
        <td><%= user.name %></td>
      </tr>
      <tr>
        <td>introduction</td>
        <td><%= user.introduction %></td>
      </tr>
      <tr>
        <td>follows</td>
        <td><%= link_to follows_user_path(user) do %><%= user.follower.count %><% end %></td>
      </tr>
      <tr>
        <td>followers</td>
        <td><%= link_to followers_user_path(user) do %><%= user.followed.count %><% end %></td>
      </tr>
      <tr>
        <% if current_user.following?(user) %>
          <td><%= link_to 'フォロー外す', unfollow_path(user.id), method: :post, class: "btn btn-lg btn-warning" %></td><td></td>
        <% else %>
          <td><%= link_to 'フォローする', follow_path(user.id), method: :post, class: "btn btn-lg btn-primary" %></td><td></td>
        <% end %>
      </tr>
  </tbody>
</table>
<div class="row">
  <% if user.id == current_user.id %>
    <p><%= link_to "", edit_user_path(current_user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %></p>
  <% end %>
</div>

<h2>New book</h2>

<%= form_for (book) do |f| %>

  <% if book.errors.any? %>
    <div id="error_explanation" class="alert aleart-danger">
    <h2><%= book.errors.count %>errors prohibited this obj from being saved:</h2>
      <ul>
        <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field row">

    <h4>Title</h4>
    <%= f.text_field :title %>
  </div>

  <div class="field row">
    <h4>Opinion</h4>
    <%= f.text_area :body %>
  </div>

  <div class="actions row">
    <%= f.submit 'Create Book' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="body">
  <div class="container">
    <div class="row">
      <div class="col-xs-3">

        <h2>User info</h2>

        <%= form_for @user do |f| %>
          <table class="table">
            <tbody>
              <% if @user.errors.any? %>
                <div id="error_explanation" class="alert aleart-danger">
                <h2><%= @user.errors.count %>errors prohibited this obj from being saved:</h2>
                  <ul>
                    <% @user.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>
              <tr>
                <th>Name <%= f.text_field :name %></th>
              </tr>
              <tr>
              	<th>Image <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form", fallback: "no_image.jpg" %></th>
              </tr>
              <tr>
                <th>Introduction <%= f.text_area :introduction %></th>
              </tr>
              <tr>
                <th><%= f.submit 'Update User' %></th>
              </tr>
            </tbody>
          </table>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<div class="body">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <h2>Follower Users</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan="4"></th>
            </tr>
          </thead>
          <tbody>
            <% @user.follower_user.where.not(id: current_user.id).each do |user| %>
            <tr>
              <td><%= attachment_image_tag user, :profile_image, size: "50x50", class: "img-rounded pull-left", fallback: "no_image.jpg" %></td>
              <td><%= user.name %></td>
              <td>フォロー数：<%= user.follower.count %></td>
              <td>フォロワー数：<%= user.followed.count %></td>
              <% if current_user.following?(user) %>
                <td><%= link_to 'フォロー外す', unfollow_path(user.id), method: :post %></td>
              <% else %>
                <td><%= link_to 'フォローする', follow_path(user.id), method: :post %></td>
              <% end %>
              <td><%= link_to 'Show', user_path(user) %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/users/follows.html.erb
<div class="body">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <h2>Follow Users</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan="4"></th>
            </tr>
          </thead>
          <tbody>
            <% @user.following_user.where.not(id: current_user.id).each do |user| %>
            <tr>
              <td><%= attachment_image_tag user, :profile_image, size: "50x50", class: "img-rounded pull-left", fallback: "no_image.jpg" %></td>
              <td><%= user.name %></td>
              <td>フォロー数：<%= user.follower.count %></td>
              <td>フォロワー数：<%= user.followed.count %></td>
                <% if current_user.following?(user) %>
                  <td><%= link_to 'フォロー外す', unfollow_path(user.id), method: :post %></td>
                <% else %>
                   <td><%= link_to 'フォローする', follow_path(user.id), method: :post %></td>
                <% end %>
              <td><%= link_to 'Show', user_path(user) %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="body">
  <div class="container">
    <div class="row">
      <div class="col-xs-3">

      <%= render 'side', user: current_user, book: @book %>

      </div>
      <div class="col-xs-9">
      <h2>Users</h2>

      <%= render 'index', users: @users %>

      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="body">
  <div class="container">
    <div class="row">
      <div class="col-xs-3">
        <%= render 'users/side', user: @user, book: @book %>
      </div>
      <div class="col-xs-9">
        <h2>Books</h2>
        <%= render 'books/index', books: @user.books %>
      </div>
    </div>
  </div>
</div>