config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :books, except: [:new] do
  	resource :favorites, only: [:create, :destroy]
  	resource :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :follows, :followers
    end
  end

  post 'follow/:id' => 'relationships#follow', as: 'follow'
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'

  get '/search', to: 'search#search'

  get "home/about" => 'homes#about'
  root 'homes#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :favorites, dependent: :destroy
	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end
	has_many :book_comments, dependent: :destroy
	validates :title, presence: true
	validates :body, presence: true
	validates :body, length: { maximum:200 }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!
  before_action :correct_book, only: [:edit]

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created successfully "
      redirect_to book_path(@book)
    else
      @books = Book.all
      render :index
    end
  end

  def index
    @book = Book.new
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated successfully."
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def correct_book
    book = Book.find(params[:id])
    if book.user != current_user
      redirect_to books_path
    end
  end

  def book_params
  params.require(:book).permit(:title, :body, :user_id)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<td>
  <%= link_to user_path(book.user) do %>
    <%= attachment_image_tag book.user, :profile_image, size: "50x50", class: "img-rounded pull-left", fallback: "no_image.jpg" %><br>
    <%= book.user.name %>
  <% end %>
</td>
<td>
	<%= link_to book_path(book.id) do %>
		<%= book.title %>
	<% end %>
</td>
<td><%= book.body %></td>
<% if book.favorited_by?(current_user) %>
<td>
<%= link_to book_favorites_path(book, redirect_id: 0), method: :delete, remote: true do %>
  <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
  <%= book.favorites.count %>
<% end %>
</td>
<% else %>
<td>
<%= link_to book_favorites_path(book, redirect_id: 0), method: :post, remote: true do %>
  <i class="fa fa-heart" aria-hidden="true" style="color: gray;"></i>
  <%= book.favorites.count %>
<% end %>
</td>
<% end %>
<td>
  <div class="comment-count">コメント数：<%= book.book_comments.count %></div>
</td>

app/views/books/_comment.html.erb
<% book_comments.each do |book_comment| %>
<tr class="comment">
  <div class="comment-body bb">
    <td class="comment-avatar">
      <%= attachment_image_tag book_comment.user, :profile_image, size: "50x50", class: "img-rounded pull-left", fallback: "no_image.jpg" %><br>
      <%= book_comment.user.name %>
    </td>
    <td class="comment-entry"><%= book_comment.comment %></td>
    <% if book_comment.user_id == current_user.id %>
      <td><%= link_to "Destroy", book_book_comments_path(book_comment), method: :delete, remote: true, class: "btn-sm btn-danger destroy" %></td>
    <% end %>
  </div>
</tr>
<% end %>

app/views/books/_detail.html.erb
<td>
  <%= link_to user_path(book.user) do %>
    <%= attachment_image_tag book.user, :profile_image, size: "50x50", class: "img-rounded pull-left", fallback: "no_image.jpg" %><br>
    <%= book.user.name %>
  <% end %>
</td>
<td><%= book.title %></td>
<td><%= book.body %></td>
<% if book.favorited_by?(current_user) %>
<td>
  <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
    <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
    <%= book.favorites.count %>
  <% end %>
</td>
<% else %>
<td>
  <%= link_to book_favorites_path(book), method: :post, remote: true do %>
    <i class="fa fa-heart" aria-hidden="true" style="color: gray;"></i>
    <%= book.favorites.count %>
  <% end %>
</td>
<% end %>
<td>
  <div class="comment-count">コメント数：<%= book.book_comments.count %></div>
</td>
<% if book.user_id == current_user.id %>
  <td><%= link_to "Edit", edit_book_path %></td>
  <td><%= link_to "Destroy", book_path, method: :delete, "data-confirm" => "本当に消しますか？" %></td>
<% end %>

app/views/books/_index.html.erb
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="4"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
    <tr class="book_<%= book.id %>">
      <%= render 'books/book', book: book %>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class="body">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1>Editing Book</h1>

        <% if @book.errors.any? %>
        <div id="error_explanation" class="alert aleart-danger">
          <h2><%= @book.errors.count %>errors prohibited this book from being saved:</h2>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>
        <% end %>

        <%= form_for @book do |f| %>
            <h4>Title</h4><br>
            <%= f.text_field :title, class: "col-xs-12" %>

        <div class="field row">
          <h4>Opinion</h4>
          <%= f.text_area :body, class: "col-xs-12" %>
        </div>

        <div class="actions row">
            <%= f.submit 'Update Book', class: "col-xs-12" %>

        <% end %>
        </div>

        <%= link_to "Show", book_path(@book.id) %> |
        <a class="back" href="/books">Back</a>
      </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="body">
  <div class="container">
    <div class="row">
      <div class="col-xs-3">
      <%= render 'users/side', user: current_user, book: @book %>
      </div>
      <div class="col-xs-9">
        <h2>Books</h2>
        <%= render 'index', books: @books %>
      </div>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="body">
  <div class="container">
    <div class="row">
      <div class="col-xs-3">

      <%= render 'users/side', user: current_user, book: Book.new %>

      </div>
      <div class="col-xs-9">
      <h2>Book detail</h2>
        <table class="table table-hover table-inverse">
          <tbody>
            <tr class="book_<%= @book.id %>">
              <%= render 'detail', book: @book %>
            </tr>
          </tbody>
        </table>
        <table>
          <tbody class="comment_<%= @book.id %>">
            <%= render 'comment', book_comments: @book.book_comments %>
          </tbody>
        </table><br>
        <%= form_with mehod: :post, model:[@book, @book_comment], data: {remote: true} do |f| %>
          <div class="row">
            <div class="col-sm-12">
              <%= f.text_area :comment, rows:'5', class: "form-control", placeholder: "コメントをここに" %>
            </div>
          </div>
          <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
        <% end %>
      </div>
    </div>
  </div>
</div>